plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'groovy'
    id "com.gradle.plugin-publish" version "1.2.1"
}

group = 'org.wpilib'
version = '2027.0.0'

if (project.hasProperty('publishVersion')) {
    version = project.publishVersion
}

repositories {
    maven {
        url = "https://plugins.gradle.org/m2/"
    }
    mavenLocal()
}

java {
    sourceCompatibility = 17
    targetCompatibility = 17
}

dependencies {
    api 'com.google.code.gson:gson:2.8.6'

    testImplementation('org.spockframework:spock-core:2.4-M6-groovy-4.0') {
        exclude group: 'org.codehaus.groovy'
    }
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation gradleTestKit()
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

gradlePlugin {
    website = 'https://github.com/wpilibsuite/gradle-cpp-vscode'
    vcsUrl = 'https://github.com/wpilibsuite/gradle-cpp-vscode'

    plugins {
        GradleVsCode {
            id = 'org.wpilib.GradleVsCode'
            displayName = 'GradleVsCode'
            implementationClass = 'org.wpilib.vscode.GradleVsCode'
            description = 'This plugin provides VS Code support for old style gradle projects.'
            tags = ['groovy', 'vscode', 'cpp', 'maven', 'frc', 'wpilib']
        }
    }
}

wrapper {
    gradleVersion = '9.2.0'
}
